server {
    listen 80;
    root /usr/share/nginx/html;
    index login.html;

    location /GraduationProject/api_front/ {
        rewrite ^/GraduationProject/api_front/(.*)$ /$1 last;
    }

    location /GraduationProject/CSS/ {
        rewrite ^/GraduationProject/CSS/(.*)$ /CSS/$1 last;
    }

    location /GraduationProject/ {
        rewrite ^/GraduationProject/(.*)$ /$1 last;
    }

    location / {
        try_files $uri $uri/ /login.html;
    }
}
