apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: smart-bins-alertmanager
  namespace: monitoring
  labels:
    release: prometheus
spec:
  route:
    receiver: slack
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 1h
  receivers:
    - name: slack
      slackConfigs:
        - apiURL:
            name: slack-secret
            key: webhook-url
          channel: "#smart-bins-alerts"
          title: "Smart Bins Alert"
          text: "{{ .CommonAnnotations.description }}"