apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: smart-bins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: mohammedkhaled978/smart-bins-backend:latest
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: my-secret

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: smart-bins
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 80
      targetPort: 80

  