apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: smart-bins
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "Admin1234"
  MYSQL_DATABASE: "smart_bins_system"
  DB_HOST: "smart-bins-db.cwds8eiy6eqc.us-east-1.rds.amazonaws.com"
  DB_NAME: "smart_bins_system"
  DB_USER: "admin"
  DB_PASSWORD: "Admin1234"
  DB_PORT: "3306"