apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: smart-bins
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "root"
  MYSQL_DATABASE: "smart_bins_system"
  DB_HOST: "mysql-service"
  DB_NAME: "smart_bins_system"
  DB_USER: "root"
  DB_PASSWORD: "root"
  DB_PORT: "3306"