name: 06basic
run-name: ${{ github.actor }}
on:
  workflow_dispatch:

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy context
        run: echo ${{ toJson(github) }}
        
